config/routes.rb
Rails.application.routes.draw do

  #下記管理者側
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do

    resources :genres, only: [:index, :create, :update, :edit]
    resources :visions, only: [:index, :show, :destroy]

    resources :users, only: [:index, :show, :update] do
      collection do
        patch '/out/:id' => 'users#out', as: "out"
      end
    end
  end

  #ここから下記ユーザー側
  #トップページでログイン可能
  devise_scope :user do
      root :to => 'public/sessions#new'
  end

  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  scope module: :public do

    get 'users/search' => 'searchs#search_user'
    get 'visions/search' => 'searchs#search_vision'
    resources :chats, only: [:show, :create]

    resources :visions do
      resource :fights, only: [:create, :destroy]
      resources :vision_comments, only: [:create, :destroy, :index]
      resources :tasks, except: [:new, :show]
      patch 'tasks/:id/complete' => 'tasks#complete', as: "complete"
    end

    resources :users, only: [:new, :edit, :update, :show, :index] do
      collection do
        get '/out_check' => 'users#out_check'
        patch '/out' => 'users#out'
      end
      resource :relationships, only: [:create, :destroy]
      get 'index' => 'relationships#index', as: 'follow'
    end

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :visions

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_genre, only: [:edit, :update]
  before_action :genre_all

  def index
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save ? (redirect_to admin_genres_path) : (render :index)
  end

  def edit
  end

  def update
    @genre.update(genre_params) ? (redirect_to admin_genres_path) : (render :edit)
  end


  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def ensure_genre
    @genre = Genre.find(params[:id])
  end

  def genre_all
    @genres = Genre.all
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_form.html.erb
<div class="container-fluid mx-auto">
  <div class="row d-flex justify-content-center">
    <div class="col-3 p-3 shadow bg-white rounded genre-form h-50">
      <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>

        <div class="col mx-auto mb-4 ">
          <%= f.label :name, obj %>
        </div>

        <div class="col mx-auto  mb-4">
          <%= f.text_field :name, class: 'form-control genre_name' ,placeholder: "Name" %>
          <%= render "public/shared/error_messages", resource: @genre, attribute: :name %>
        </div>

        <div class="col mb-3 text-right">
          <%= f.submit submit, class: "btn btn-outline-success " %>
        </div>

      <% end %>
    </div>

    <div class="col-3">
      <% @genres.each do |genre| %>
        <div class="col-8 shadow p-2 mb-3 bg-white rounded mx-auto">
      <div class="d-flex justify-content-between my-auto">
            <%= genre.name %>
            <%= link_to "Edit", edit_admin_genre_path(genre.id), class: "btn btn-outline-danger" %>
           </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/_search.html.erb
<div class="container-fluid">
  <%= form_with url: visions_path, method: :get do |f| %>

    <div class="row d-flex justify-content-end">
      <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), {include_blank: "カテゴリー" }, class: "col-lg-4 col-sm-8 col text-center btn-sm genre-font" %>
      <button class="btn btn-outline-secondary rounded btn-sm ml-1"><i class="fas fa-search"></i></button>
    </div>

  <% end %>
</div>

app/views/admin/genres/edit.html.erb
<%= render "form", submit: "Edit", obj: "Category" %>

app/views/admin/genres/index.html.erb
<%= render "form", submit: "ADD", obj: "New Category" %>