config/routes.rb
Rails.application.routes.draw do

  #下記管理者側
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do

    resources :genres, only: [:index, :create, :update, :edit]
    resources :visions, only: [:index, :show, :destroy]

    resources :users, only: [:index, :show, :update] do
      collection do
        patch '/out/:id' => 'users#out', as: "out"
      end
    end
  end

  #ここから下記ユーザー側
  #トップページでログイン可能
  devise_scope :user do
      root :to => 'public/sessions#new'
  end

  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  scope module: :public do

    get 'users/search' => 'searchs#search_user'
    get 'visions/search' => 'searchs#search_vision'
    resources :chats, only: [:show, :create]

    resources :visions do
      resource :fights, only: [:create, :destroy]
      resources :vision_comments, only: [:create, :destroy, :index]
      resources :tasks, except: [:new, :show]
      patch 'tasks/:id/complete' => 'tasks#complete', as: "complete"
    end

    resources :users, only: [:new, :edit, :update, :show, :index] do
      collection do
        get '/out_check' => 'users#out_check'
        patch '/out' => 'users#out'
      end
      resource :relationships, only: [:create, :destroy]
      get 'index' => 'relationships#index', as: 'follow'
    end

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vision.rb
class Vision < ApplicationRecord
  has_one_attached :production_image
  belongs_to :user
  belongs_to :genre
  has_many :tasks, dependent: :destroy
  has_many :fights, dependent: :destroy
  has_many :vision_comments, dependent: :destroy

  validates :title, length: { minimum: 2, maximum: 20 }, presence: true
  validates :body, length: { maximum: 100 }
  validates :finish_on, presence: true
  validate :dae_before_start

  enum release_status: { public: 0, private: 1 }, _prefix: true

  scope :still, -> { where(finish_status: false) }
  scope :finish, -> { where(finish_status: true) }
  scope :no_private, -> { where(release_status: false) }
  scope :on_private, -> { where(release_status: true) }

  def self.search_for(content)
    Vision.where(['title LIKE ? OR body LIKE ?', "%#{content}%","%#{content}%"])
  end

  def dae_before_start
    return if finish_on.blank?
    errors.add(:finish_on, "は本日以降を選択してください") if finish_on < Date.today
  end

  def get_production_image
    if production_image.attached?
      production_image
    else
      'no_production_image.jpg'
    end
  end

end

app/controllers/admin/visions_controller.rb
class Admin::VisionsController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_vision, only: [:show, :destroy]

  def index
    @visions = Vision.all
  end

  def show
    @tasks = @vision.tasks.order(completion_on: "ASC")
  end

  def destroy
    @vision.delete
    redirect_to admin_visions_path
  end

  private

    def vision_params
      params.require(:vision)
    end
  
    def ensure_vision
      @vision = Vision.find(params[:id])
    end
end

app/helpers/admin/visions_helper.rb
module Admin::VisionsHelper
end

app/views/admin/visions/_index.html.erb
<div class="container-fluid">
  <% if @visions.present? %>
    <% @visions.each do |vision| %>
      <div class="row col-10 shadow p-2 mb-3 bg-white rounded mx-auto">

        <div class="col-2 d-flex justify-content-center my-auto">
          <%= link_to admin_user_path(vision.user), class: "text-decoration-none" do %>
            <div class="profile_image pb-3"><%= image_tag vision.user.get_profile_image, size: "100x100", class: "rounded-circle" %></div>
            <div class="text-center text-dark"><%= vision.user.name %></div>
          <% end %>
        </div>

        <%= link_to admin_vision_path(vision), class: "col-5 text-center my-auto text-dark text-decoration-none" do %>
          <p class="p-2 bg-light text-dark rounded"><%= vision.title %></p>
        <% end %>

        <div class="col-3 d-flex justify-content-center my-auto">
        <!--タスクの数によって分岐-->
          <!--タスク0個の場合-->
          <% if vision.tasks.count == 0 %>
            <p class="text-danger">No Task</p>
        
          <!--タスクがすべて完了時ている時の場合-->
          <% elsif vision.tasks.where(completion_status: true).count == vision.tasks.count %>
            <p><%= image_tag vision.get_production_image, class: "rounded production-image" %></p>
        
          <!--未完了のタスクがある場合-->
          <% else %>
            <!--タスクの達成割合グラフ-->
            <canvas id="<%= vision.id %>"></canvas>
            <script>
              var ctx = document.getElementById("<%= vision.id %>");
              var data = [<%= vision.tasks.where(completion_status: true).count %>, <%= vision.tasks.where(completion_status: false).count %>]
              var myLineChart = new Chart(ctx, {
                type: 'pie' ,
                data: {
                  labels: ['達成', '未達成'],
                  datasets: [{
                    data: data,
                    backgroundColor: ['#48f', '#e03448'],
                  }],
                },
                Options: {
                  pie: {
                  }
                }
              });
            </script>
          <% end %>
        </div>

        <div class="col text-center my-auto">
          <%= render "public/visions/count", vision: vision %>
        </div>

      </div>
    <% end %>
  <% else %>
    <h3>Nothing WAY</h3>
  <% end %>
</div>

app/views/admin/visions/index.html.erb
<div class="container">
  <%= render "index", visions: @visions %>
</div>

app/views/admin/visions/show.html.erb
<div class="container mx-auto my-auto">
  <div class="row col-10 shadow p-3 mb-3 bg-white rounded mx-auto bg-light">

    <div class="col-3 d-flex justify-content-center my-auto ">
      <%= link_to admin_user_path(@vision.user) do %>
        <div class="profile_image pb-3"><%= image_tag @vision.user.get_profile_image, size: "150x150", class: "rounded-circle" %></div>
        <div class="text-center text-dark"><%= @vision.user.name %></div>
      <% end %>
    </div>

    <div class="col-9">

      <div class="row mb-4">
        <div class="col-8 mr-auto d-flex my-auto">
          <h4 class="mr-3"><%= @vision.title %></h4>
        </div>

        <div class="col-4 p-2 text-center">
          <i class="fas fa-tags fa-2x mr-3"></i>
          <sapn><%= @vision.genre.name %></span>
        </div>
      </div>

      <div class="row">
        <div class="col-4"><%= @vision.body %></div>

        <div class="col-3  text-center my-auto ">
          <%= render "public/visions/count", vision: @vision %>
        </div>

        <div class="col-5 text-center my-auto">
          <%= link_to 'Destroy',  admin_vision_path(@vision.id), method: :delete, data: { confirm: '本当にこのビジョンを消しますか？' }, class: "btn btn-outline-danger btn-lg" %>
        </div>
      </div>

    </div>
  </div>
</div>