config/routes.rb
Rails.application.routes.draw do

  #下記管理者側
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do

    resources :genres, only: [:index, :create, :update, :edit]
    resources :visions, only: [:index, :show, :destroy]

    resources :users, only: [:index, :show, :update] do
      collection do
        patch '/out/:id' => 'users#out', as: "out"
      end
    end
  end

  #ここから下記ユーザー側
  #トップページでログイン可能
  devise_scope :user do
      root :to => 'public/sessions#new'
  end

  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  scope module: :public do

    get 'users/search' => 'searchs#search_user'
    get 'visions/search' => 'searchs#search_vision'
    resources :chats, only: [:show, :create]

    resources :visions do
      resource :fights, only: [:create, :destroy]
      resources :vision_comments, only: [:create, :destroy, :index]
      resources :tasks, except: [:new, :show]
      patch 'tasks/:id/complete' => 'tasks#complete', as: "complete"
    end

    resources :users, only: [:new, :edit, :update, :show, :index] do
      collection do
        get '/out_check' => 'users#out_check'
        patch '/out' => 'users#out'
      end
      resource :relationships, only: [:create, :destroy]
      get 'index' => 'relationships#index', as: 'follow'
    end

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :registerable, :recoverable, :rememberable, :validatable,
         :database_authenticatable, authentication_keys: [:name]

  has_one_attached :profile_image

  has_many :visions
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォロー一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  has_many :fights
  has_many :vision_comments, dependent: :destroy

  # 退会していないユーザーの特定
  scope :no_outcheck, -> { joins(:visions).where(user_status: false) }

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }, presence: true
  validates :biography, length: { maximum: 50 }

  # プロフィール写真の有無時の表示
  def get_profile_image
    if profile_image.attached?
      profile_image
    else
      'no_image.jpg'
    end
  end

　# フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  # ユーザー検索方法
  def self.search_for(content)
    User.where(['name LIKE ?', "%#{content}%"])
  end

  # ユーザーがファイトを押しているかを判断
  def fighted_by?(vision_id)
    fights.where(vision_id: vision_id).exists?
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_user, except: [:index]

  def index
    @users = User.all
  end

  def show
    @visions = @user.visions.order(finish_on: "ASC")
  end

  # ユーザーの退会
  def out
    @user.update(user_status: true)
    reset_session
    redirect_to admin_users_path
  end

  private

    def ensure_user
      @user = User.find(params[:id])
    end
  
    def user_params
      params.require(:user).permit(:user_status)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container-fluid mx-auto text-center">
  <% @users.each do |user| %>
    <div class="row col-5 shadow p-2 mb-3 bg-white rounded mx-auto">
      <%= link_to admin_user_path(user), class: "row col-12 text-decoration-none" do %>
      
        <div class="profile_image col"><%= image_tag user.get_profile_image, size: "100x100", class: "rounded-circle" %></div>
        
        <div class="col-3 text-left text-dark my-auto"><%= user.name %></div>

        <div class="col-3 text-center text-dark my-auto">Way <%= user.visions.count %></div>
        
        <div class="col-3 text-center my-auto">
          <% if user.user_status? %>
            <P class="text-danger">退会済み</P>
          <% else %>
            <P class="text-success">活動中</P>
          <% end %>
        </div>
        
      <% end %>
    </div>
	<% end %>
</div>

app/views/admin/users/show.html.erb
<div class="container-fluid mx-auto">
  <div class="row d-flex justify-content-center">
    <div class="col-2 p-3 shadow bg-white rounded profile-tag">
      
      <div class="text-center">
        <%= image_tag @user.get_profile_image, size: "200x200", class: "rounded-circle" %>
      </div>
      
      <div class="row">
        
        <div class="col-6">
          <h4 class="mt-3"><%= @user.name %></h4>
          <h6><span><i class="fas fa-birthday-cake"></i></span><%= @user.birthday.strftime('%Y/%m/%d') %></h6>
        </div>
        
        <div class="col-6 my-auto text-center">
          <% unless @user.user_status? %>
            <%= link_to "強制退会", out_admin_users_path(@user), method: :patch, "data-confirm" => "OKを押すと退会処理がされます。本当によろしいですか？", class: 'btn btn-outline-danger rounded follow-font' %>
          <% end %>
        </div>
      </div>
      
      <p><%= @user.biography %><p>
        
      <div class="row col-12 text-center p-0 m-0">
        <p class="col-4 p-0 mx-auto">Posts</p>
        <p class="col-4 p-0 mx-auto">Follow</p>
        <p class="col-4 p-0 mx-auto">Followers</p>
        <p class="col-4"><%= @user.visions.count %></p>
        <p class="col-4"><%= @user.followings.count %></p>
        <p class="col-4"><%= @user.followers.count %></p>
      </div>
    </div>
    
    <div class="col-7">
      <%= render "admin/visions/index", visions: @visions %>
    </div>
    
  </div>
</div>