config/routes.rb
Rails.application.routes.draw do

  #下記管理者側
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do

    resources :genres, only: [:index, :create, :update, :edit]
    resources :visions, only: [:index, :show, :destroy]

    resources :users, only: [:index, :show, :update] do
      collection do
        patch '/out/:id' => 'users#out', as: "out"
      end
    end
  end

  #ここから下記ユーザー側
  #トップページでログイン可能
  devise_scope :user do
      root :to => 'public/sessions#new'
  end

  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  scope module: :public do

    get 'users/search' => 'searchs#search_user'
    get 'visions/search' => 'searchs#search_vision'
    resources :chats, only: [:show, :create]

    resources :visions do
      resource :fights, only: [:create, :destroy]
      resources :vision_comments, only: [:create, :destroy, :index]
      resources :tasks, except: [:new, :show]
      patch 'tasks/:id/complete' => 'tasks#complete', as: "complete"
    end

    resources :users, only: [:new, :edit, :update, :show, :index] do
      collection do
        get '/out_check' => 'users#out_check'
        patch '/out' => 'users#out'
      end
      resource :relationships, only: [:create, :destroy]
      get 'index' => 'relationships#index', as: 'follow'
    end

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, authentication_keys: [:email]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 150 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :vision
  validates :comment, presence: true, length: { maximum: 100 }
end

app/models/fight.rb
class Fight < ApplicationRecord
  belongs_to :user
  belongs_to :vision

  validates_uniqueness_of :vision_id, scope: :user_id
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :visions

  validates :name, presence: true, uniqueness: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
 
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :vision

  validates :content, length: { minimum: 2, maximum: 30 }, presence: true
  validates :completion_on, presence: true
  validate :date_before_start
  validate :date_before_finish
  
  # 未完了タスクの絞り込み
  scope :yet, -> { where(completion_status: false) }
  # 完了タスクの絞り込み
  scope :complete, -> { where(completion_status: true) }
  
  
  def completion_status_method
    if completion_status == true
      'Conmplete!!'
    else
      'Conmplete??'
    end
  end

  # 完了日が本日以降出ない時のバリデーション
  def date_before_start
    return if completion_on.blank?
    errors.add(:completion_on, "は本日以降を選択してください") if completion_on < Date.today
  end

  # 完了日が達成日以前出ない時のバリデーション
  def date_before_finish
    return if completion_on.blank?
    errors.add(:completion_on, "はWay達成日以前を選択してください") if  completion_on >= vision.finish_on
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :registerable, :recoverable, :rememberable, :validatable,
         :database_authenticatable, authentication_keys: [:name]

  has_one_attached :profile_image

  has_many :visions
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォロー一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  has_many :fights
  has_many :vision_comments, dependent: :destroy

  # 退会していないユーザーの特定
  scope :no_outcheck, -> { joins(:visions).where(user_status: false) }

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }, presence: true
  validates :biography, length: { maximum: 50 }

  # プロフィール写真の有無時の表示
  def get_profile_image
    if profile_image.attached?
      profile_image
    else
      'no_image.jpg'
    end
  end

　# フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  # ユーザー検索方法
  def self.search_for(content)
    User.where(['name LIKE ?', "%#{content}%"])
  end

  # ユーザーがファイトを押しているかを判断
  def fighted_by?(vision_id)
    fights.where(vision_id: vision_id).exists?
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/vision.rb
class Vision < ApplicationRecord
  has_one_attached :production_image
  belongs_to :user
  belongs_to :genre
  has_many :tasks, dependent: :destroy
  has_many :fights, dependent: :destroy
  has_many :vision_comments, dependent: :destroy

  validates :title, length: { minimum: 2, maximum: 20 }, presence: true
  validates :body, length: { maximum: 100 }
  validates :finish_on, presence: true
  validate :dae_before_start

  enum release_status: { public: 0, private: 1 }, _prefix: true

  scope :still, -> { where(finish_status: false) }
  scope :finish, -> { where(finish_status: true) }
  scope :no_private, -> { where(release_status: false) }
  scope :on_private, -> { where(release_status: true) }

  def self.search_for(content)
    Vision.where(['title LIKE ? OR body LIKE ?', "%#{content}%","%#{content}%"])
  end

  def dae_before_start
    return if finish_on.blank?
    errors.add(:finish_on, "は本日以降を選択してください") if finish_on < Date.today
  end

  def get_production_image
    if production_image.attached?
      production_image
    else
      'no_production_image.jpg'
    end
  end

end

app/models/vision_comment.rb
class VisionComment < ApplicationRecord
  belongs_to :user
  belongs_to :vision
  validates :comment, presence: true, length: { maximum: 100 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_genre, only: [:edit, :update]
  before_action :genre_all

  def index
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save ? (redirect_to admin_genres_path) : (render :index)
  end

  def edit
  end

  def update
    @genre.update(genre_params) ? (redirect_to admin_genres_path) : (render :edit)
  end


  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def ensure_genre
    @genre = Genre.find(params[:id])
  end

  def genre_all
    @genres = Genre.all
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_user, except: [:index]

  def index
    @users = User.all
  end

  def show
    @visions = @user.visions.order(finish_on: "ASC")
  end

  # ユーザーの退会
  def out
    @user.update(user_status: true)
    reset_session
    redirect_to admin_users_path
  end

  private

    def ensure_user
      @user = User.find(params[:id])
    end
  
    def user_params
      params.require(:user).permit(:user_status)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin/visions_helper.rb
module Admin::VisionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<% if admin_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-dark bg- mb-4">
    <div class="container">
      <a class="navbar-brand" href="/"><span><i class="fab fa-airbnb"></i></span></a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav text-right">
          <li class="mx-2"><%= link_to '投稿一覧', admin_visions_path %></li>
          <li class="mx-2"><%= link_to '会員一覧',  admin_users_path %></li>
          <li class="mx-2"><%= link_to 'ジャンル一覧',  admin_genres_path %></li>
          <li class="mx-2 sm-ml-2"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  </nav>

<% elsif user_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <div class="container d-flex justify-content-between">
      <div class="col">
        <%= link_to user_path(current_user.id) do %>
          <%= image_tag current_user.get_profile_image, size: "50x50", class: "rounded-circle" %>
        <% end %>
      </div>

      <div class="col text-center">
        <%= link_to visions_path do %><%= image_tag ("AdobeStock_325527702.jpg"), class: "header-logo" %><% end %>
      </div>

      <div class="col text-right">
        <span><%= link_to new_vision_path, class: 'text-light' do %><i class="fas fa-plus-circle fa-2x"></i><% end %></span>
        <%= link_to destroy_user_session_path, method: :delete, class: 'text-light' do %><i class="fas fa-sign-out-alt fa-2x ml-2 ml-sm-4"></i><% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WayMe</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  </head>

  <body>
    <% unless current_page?(root_path) || current_page?(new_user_registration_path) || current_page?(new_admin_session_path) %>
      <header>
        <%= render "layouts/header" %>
      </header>
    <% end %>
    
    <main>
      <%= yield %>
    </main>
    
  </body>
</html>